name: Deploy API
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Deploy Function
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            
            const functionPath = path.join(process.env.GITHUB_WORKSPACE, '.github/api/generate.js');
            const functionContent = fs.readFileSync(functionPath, 'utf8');
            
            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'api/generate.js',
              message: 'Deploy API function',
              content: Buffer.from(functionContent).toString('base64'),
              branch: 'gh-pages'
            });

        env:
          GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
